services:
  api:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video]
